# Generated by Django 3.1.5 on 2021-01-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, null=True, verbose_name='Отчество')),
                ('grade', models.IntegerField(choices=[(2, 'Неуд'), (3, 'Удовл'), (4, 'Хор'), (5, 'Отл')], default=2, verbose_name='Успеваемость')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
